## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 1.0
  - nightly
notifications:
  email: false
git:
  depth: 99999999

# uncomment the following lines to allow failures on nightly julia
# (tests will run but not make your overall status red)
matrix:
  allow_failures:
  - julia: nightly

# uncomment and modify the following lines to manually install system packages
addons:
  apt: # apt-get for linux
    packages:
    - gfortran  # for Dierckx in the testing script
before_script: # homebrew for mac
#  - if [ $TRAVIS_OS_NAME = osx ]; then brew cask uninstall oclint; fi  # https://github.com/travis-ci/travis-ci/issues/8826
  - if [ $TRAVIS_OS_NAME = osx ]; then brew install gcc; fi  # for Dierckx in the testing script

## uncomment the following lines to override the default test script
#script:
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("TwoFAST"); Pkg.test("TwoFAST"; coverage=true)'

after_success:
  # push coverage results to Coveralls
  - julia -e 'import TwoFAST; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'import TwoFAST; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
