name = "TwoFAST"
uuid = "0dd23c3e-f403-11e8-3e11-4dddf690af97"
authors = ["Henry Gebhardt <hsggebhardt@gmail.com>"]
version = "0.1.1"

[deps]
ArbNumerics = "7e558dbc-694d-5a72-987c-6f4ebed21442"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
ArbNumerics = "1.0"
FFTW = "1.0"
SpecialFunctions = "0.8.0, 0.9, 0.10"
julia = "1.0"

[extras]
Dierckx = "39dd38d3-220a-591b-8e3c-4c3a8c710a94"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Dierckx", "Test"]
