name = "TwoFAST"
uuid = "0dd23c3e-f403-11e8-3e11-4dddf690af97"
authors = ["Henry Gebhardt <hsggebhardt@gmail.com>"]
version = "0.1.0"

[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
IncGammaBeta = "5087d2c0-5ad2-51de-b1ef-eaf82f0743fd"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
